Add filtering functionality to bids2table
childmindresearch/bids2table pull request #6
Opened 2023-07-10 16:31 UTC by ReinderVosDeWael

This PR adds filtering functionality to bids2table. It can be invoked with lists of values (that are considered an OR), or single values (equivalent to a list of a single value). See example usage below.

```python
import bids2table

bids2table.bids2table(BIDS_DIR, filters={'datatype': ['func', 'anat'], 'suffix': 'T1w'})
```

Specifically, this PR adds the following:
- A `_filter` method to `_bids2table.py`
- Unit tests for `_filter`, including a workflow to run them
- Updates the example notebook to include the new functionality
- A `exceptions.py` for custom exceptions.

2023-07-11 13:04 UTC, clane9 requested changes
Thanks for the PR @ReinderVosDeWael! Left a couple comments. And then I'll be glad to merge.

2023-07-11 13:04 UTC, clane9 commented on bids2table/_bids2table.py
> +            raise exceptions.InvalidFilterError(
I don't think I would catch and re-raise a custom exception. I would just let the `KeyError` be raised. Just as informative I think and less code.

2023-07-11 13:04 UTC, clane9 commented on .github/workflows/test.yaml
Let's not add CI in this PR. I'd rather do that separately.

2023-07-11 13:31 UTC, ReinderVosDeWael commented on pyproject.toml
> +pythonpath = [
It allows for testing without installation. It was useful locally, but I'll remove it.

2023-07-11 13:47 UTC, ReinderVosDeWael commented on example/example.ipynb
> +      "0it [00:00, ?it/s]\n",
Fixed; not sure how that sloppiness slipped through.

2023-07-11 13:47 UTC, ReinderVosDeWael commented on .github/workflows/test.yaml
Removed CI

2023-07-11 14:38 UTC, clane9 commented on example/example.ipynb
> +   "outputs": [],
The table generation progress log is now missing. Not sure why. Perhaps a restart and run all would fix it?

2023-08-07 22:29 UTC, clane9 commented
Superseded by #17.

2023-08-07 22:29 UTC, closed without merging